version: "3.8"

services:
  todo-service:
    image: todo-service
    build: ../todo-service
    container_name: todo-service
    environment:
      - PORT=8001
    ports:
      - 8001:8001

  comment-service:
    image: comment-service
    build: ../comment-service
    container_name: comment-service
    environment:
      - PORT=8002
    ports:
      - 8002:8002

  todo-spa:
    image: todo-spa
    build: ../todo-spa
    container_name: todo-spa
    ports:
      - "3000:3000"
